# This file is generated by cargo2rulesmk.py --run --features .
# Do not modify this file as changes will be overridden on upgrade.

LOCAL_DIR := $(GET_LOCAL_DIR)
MODULE := $(LOCAL_DIR)
MODULE_CRATE_NAME := log
MODULE_SRCS := \
	$(LOCAL_DIR)/src/lib.rs \

MODULE_RUST_EDITION := 2015
MODULE_RUSTFLAGS += \
	--cfg 'atomic_cas' \
	--cfg 'has_atomics' \

MODULE_LIBRARY_DEPS := \
	external/rust/crates/cfg-if \
	external/rust/crates/serde \

include make/library.mk
