# This file is generated by cargo2rulesmk.py --run --config cargo2rulesmk.json.
# Do not modify this file as changes will be overridden on upgrade.

LOCAL_DIR := $(GET_LOCAL_DIR)
MODULE := $(LOCAL_DIR)
MODULE_CRATE_NAME := log
MODULE_SRCS := \
	$(LOCAL_DIR)/src/lib.rs \

MODULE_RUST_EDITION := 2015
MODULE_RUSTFLAGS += \
	--cfg 'atomic_cas' \
	--cfg 'has_atomics' \

MODULE_LIBRARY_DEPS := \
	external/rust/crates/cfg-if \
	external/rust/crates/serde \

ifeq ($(call TOBOOL,$(TRUSTY_USERSPACE)),false)

# avoid cyclic dependence by adding dependencies manually
MODULE_ADD_IMPLICIT_DEPS := false

MODULE_DEPS := \
	trusty/user/base/lib/libcore-rust/ \
	trusty/user/base/lib/libcompiler_builtins-rust/ \

endif

include make/library.mk
